[package]
name = "tcge-opengl"
version = "0.1.0"
authors = ["Longor1996 <lalongok@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
gl_generator = "0.11.0"

[features]
debug = []
