name: Rust

on: [push]

jobs:
  build:
    name: Build and test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --verbose
    - name: Run tests
      run: cargo test --verbose --verbose
